#!/bin/env bash
# Bash script to install nginx webserver 

# Install nginx
apt-get update
apt-get install -y nginx

# Set up nginx configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        return 200 'Hello World!';
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart nginx using kill command
sudo kill -s HUP $(pgrep nginx)

exit 0
