#!/usr/bin/env bash
# Script to configure Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo at-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

boro_add_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/borisngong permanent;"

sudo sed -i "s/server_name _;/$boro_add_string/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
