#!/usr/bin/env bash
# Script to configure Nginx server so that /redirect_me is redirecting to another page

# Update and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Configure redirection for /redirect_me
boro_add_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/borisngong permanent;"
sudo sed -i "s/server_name _;/$boro_add_string\n\t/" /etc/nginx/sites-enabled/default

# Create custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure 404 error page
boro_add_error_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$boro_add_error_string/" /etc/nginx/sites-enabled/default

# Check Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart
