#!/usr/bin/env bash
# Script to configure Nginx server so that /redirect_me is redirecting to another page

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOT
server {
    listen 80 default_server;
    root /var/www/html;
    index index.html index.htm;

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
}
EOT

# Test the Nginx configuration
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart
