#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server

# Install and configure HAProxy on the lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# Edit the HAProxy configuration file
server_config=\
"
frontend boro_frontend
        bind *:80
        mode http
        default_backend boro_backend
backend boro_backend
        balance roundrobin
        server 382717-web-01 18.234.192.1 check
        server 382717-web-02 54.160.85.43 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by the init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test the HAProxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart

