#!/usr/bin/env bash
# Bash script to configure an Nginx server to listen on port 80

# Remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default

# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Verify Nginx configuration is okay
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart
