#!/usr/bin/env bash
# Script to configure Nginx server to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo kill "$(pgrep 'nginx' | head -1)"
