#!/usr/bin/env bash
# This scripts list the current running processes
#   Must show all processes, for all users, including those which might not have a TTY
#   Display in a user-oriented format
#   Show process hierarchy

ps -a -x -u -f
