#!/usr/bin/env bash
# Bash script that stops 4-to_infinity_and_beyond process
# You must use kill

# To get the pid
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Infinite process termination
if [ -n "$id" ]
then
	kill -15 "$id"
fi
