#!/usr/bin/env bash
# Using while loop to dispaly numbers 20 times:
#   "bad luck from China" for the 4th iteration
#   "bad luck from Japan" for the 9th iteration
#   "bad luck from Italy" for the 17th loop iteration

aggregate=1

while [ $aggregate -le 20 ]
do
  echo "$aggregate"
  case $aggregate in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( aggregate++ ))
done
