#!/usr/bin/env bash
#Configure ufw so that it blocks all incoming trafficexcept the following TCP ports:
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)

# Upgrade upgradable apps
sudo apt-get update

# Install the Uncomplicated Firewall (ufw)
sudo apt install ufw

# Set the default policy to deny incoming traffic
# This blocks all incoming connections by default
sudo ufw default deny incoming

# Set the default policy to allow outgoing traffic
# This allows all outgoing connections by default
sudo ufw default allow outgoing

# Open port 22 for incoming TCP traffic (SSH)
# This allows SSH connections to the server
sudo ufw allow 22/tcp

# Open port 443 for incoming TCP traffic (HTTPS)
# This allows HTTPS connections to the server
sudo ufw allow 443/tcp

# Open port 80 for incoming TCP traffic (HTTP)
# This allows HTTP connections to the server
sudo ufw allow 80/tcp

# Enable the firewall and apply the configured rules
sudo ufw enable

# Display the current status of the firewall
sudo ufw status
# This shows the active rules and their status
sudo ufw status verbose
